=== Domain/serviio/org/serviio/upnp/service/contentdirectory/definition/ContentDirectoryDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="ContainerClassType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CONTAINER"/>
			<xsd:enumeration value="PERSON"/>
			<xsd:enumeration value="MUSIC_ARTIST"/>
			<xsd:enumeration value="GENRE"/>
			<xsd:enumeration value="MUSIC_GENRE"/>
			<xsd:enumeration value="ALBUM"/>
			<xsd:enumeration value="MUSIC_ALBUM"/>
			<xsd:enumeration value="STORAGE_FOLDER"/>
			<xsd:enumeration value="PLAYLIST_CONTAINER"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="ItemClassType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MUSIC_TRACK"/>
			<xsd:enumeration value="PHOTO"/>
			<xsd:enumeration value="AUDIO_ITEM"/>
			<xsd:enumeration value="IMAGE_ITEM"/>
			<xsd:enumeration value="VIDEO_ITEM"/>
			<xsd:enumeration value="MOVIE"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="ContainerType">
		<xsd:choice>
			<xsd:group ref="allowed-under-container"/>
		</xsd:choice>
		<xsd:attribute name="title_key" type="xsd:string" use="required"/>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
		<xsd:attribute name="browsable" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="editable" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="containerClass" type="ContainerClassType" use="required"/>
		<xsd:attribute name="cacheRegion" type="xsd:string"	use="required"/>
	</xsd:complexType>

	<xsd:complexType name="ActionType">
		<xsd:choice>
			<xsd:group ref="allowed-under-action"/>
		</xsd:choice>
		<xsd:attribute name="command" type="xsd:string"	use="required"/>
		<xsd:attribute name="idPrefix" type="xsd:string" use="required" />
		<xsd:attribute name="containerClass" type="ContainerClassType" use="optional" />
		<xsd:attribute name="itemClass" type="ItemClassType" use="optional" />
		<xsd:attribute name="recursive" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="cacheRegion" type="xsd:string"	use="required"/>
	</xsd:complexType>

	<xsd:element name="container" type="ContainerType"/>

    <xsd:group name="allowed-root">
    	<xsd:sequence>
    		<xsd:element ref="container" minOccurs="1" maxOccurs="1"/>
    	</xsd:sequence>
    </xsd:group>

    <xsd:group name="allowed-under-container">
    	<xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
    			<xsd:element ref="action"/>
    			<xsd:element ref="container"/>
    		</xsd:choice>
    	</xsd:sequence>
    </xsd:group>

    <xsd:group name="allowed-under-action">
    	<xsd:sequence>
    		<xsd:element ref="action" minOccurs="0" maxOccurs="1"/>
    	</xsd:sequence>
    </xsd:group>

    <xsd:element name="action" type="ActionType"/>
</xsd:schema>

=== Domain/serviio/org/serviio/upnp/service/contentdirectory/definition/contentDirectoryDef.xml
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
   	xsi:noNamespaceSchemaLocation="ContentDirectoryDef.xsd"
    title_key="serviio_media_library" id="0" containerClass="CONTAINER" cacheRegion="no_cache">
    
	<container title_key="audio" id="A" editable="true" containerClass="CONTAINER" cacheRegion="no_cache"> <!-- see org.serviio.upnp.service.contentdirectory.definition.Definition for container id -->
		<container title_key="artists" id="A_A" editable="true" containerClass="CONTAINER" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.person.ListArtistInitialsCommand" idPrefix="INI" containerClass="CONTAINER" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.person.ListArtistsForInitialCommand" idPrefix="ART" containerClass="MUSIC_ARTIST" cacheRegion="local_default">
					<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAlbumsForArtistCommand" idPrefix="A" containerClass="MUSIC_ALBUM" cacheRegion="local_default">
						<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForArtistAndAlbumCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />	
					</action>
				</action>							
			</action>
		</container>
		<container title_key="album_artists" id="AL_A" editable="true" containerClass="CONTAINER" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.person.ListAlbumArtistInitialsCommand" idPrefix="INI" containerClass="CONTAINER" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.person.ListAlbumArtistsForInitialCommand" idPrefix="ART" containerClass="MUSIC_ARTIST" cacheRegion="local_default">
					<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAlbumsForAlbumArtistCommand" idPrefix="A" containerClass="MUSIC_ALBUM" cacheRegion="local_default">						
						<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForAlbumCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />
					</action>
				</action>							
			</action>
		</container>				
		<container title_key="folders" id="A_F" editable="true" containerClass="CONTAINER" cacheRegion="local_default">	
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAudioFoldersByNameCommand" idPrefix="FOL" recursive="true" containerClass="STORAGE_FOLDER" itemClass="MUSIC_TRACK" cacheRegion="local_default"/>				
		</container>	
		<container title_key="genres" id="A_G" editable="true" containerClass="CONTAINER" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAudioGenresByNameCommand" idPrefix="GEN" containerClass="MUSIC_GENRE" cacheRegion="local_default">				
				<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForGenreCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />
			</action>
		</container>
		<container title_key="composers" id="A_C" editable="true" containerClass="CONTAINER" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.person.ListComposerInitialsCommand" idPrefix="INI" containerClass="CONTAINER" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.person.ListComposersForInitialCommand" idPrefix="COM" containerClass="MUSIC_ARTIST" cacheRegion="local_default">
					<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAlbumsForComposerCommand" idPrefix="A" containerClass="MUSIC_ALBUM" cacheRegion="local_default">
						<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForComposerAndAlbumCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />	
					</action>
				</action>							
			</action>
		</container>
		<container title_key="titles" id="A_T" editable="true" containerClass="CONTAINER" cacheRegion="local_default">	
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongInitialsCommand" idPrefix="INI" containerClass="CONTAINER" cacheRegion="local_default">				
				<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForInitialCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default"/>
			</action>					
		</container> 	
		<container title_key="random" id="A_R" editable="true" containerClass="CONTAINER" cacheRegion="no_cache">	
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListRandomSongsCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="no_cache" />					
		</container>
		<container title_key="playlists" id="A_PL" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAudioPlaylistsCommand" idPrefix="PL" containerClass="PLAYLIST_CONTAINER" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForPlaylistCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default"/>
			</action>
		</container>	 
		<container title_key="online" id="A_OF" editable="true" containerClass="CONTAINER" cacheRegion="no_cache">
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAudioOnlineContentCommand" idPrefix="FOL" recursive="true" containerClass="STORAGE_FOLDER" itemClass="MUSIC_TRACK" cacheRegion="no_cache"/>
		</container>	 
		
		<!-- XBOX360 search only categories  -->
		<container title_key="All songs" id="A_S" containerClass="CONTAINER" browsable="false" cacheRegion="local_default">								
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAllSongsCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default"/>								
		</container> 		
		<container title_key="Artist Songs" id="A_AS" containerClass="CONTAINER" browsable="false" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.person.ListArtistsByNameCommand" idPrefix="ART_S" containerClass="MUSIC_ARTIST" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForArtistCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />				
			</action>
		</container>	
		<container title_key="All albums" id="A_ALB" containerClass="CONTAINER" browsable="false" cacheRegion="local_default">		
			<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListAllAlbumsCommand" idPrefix="ALB" containerClass="MUSIC_ALBUM" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.audio.ListSongsForAlbumCommand" idPrefix="S" itemClass="MUSIC_TRACK" cacheRegion="local_default" />				
			</action>				
		</container>			
	</container>
	<container title_key="image" id="I" editable="true" containerClass="CONTAINER" cacheRegion="no_cache"> <!-- see org.serviio.upnp.service.contentdirectory.definition.Definition for container id -->
		<container title_key="albums" id="I_A" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.image.ListFlatImageFoldersByNameCommand" idPrefix="ALB" containerClass="CONTAINER" cacheRegion="local_default">				
				<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesForFolderCommand" idPrefix="I" itemClass="PHOTO" cacheRegion="local_default" />
			</action>
		</container>	
		<container title_key="folders" id="I_F" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImageFoldersByNameCommand" idPrefix="FOL" recursive="true" containerClass="STORAGE_FOLDER" itemClass="PHOTO" cacheRegion="local_default" />				
		</container>	
		<container title_key="year" id="I_Y" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesCreationYearsCommand" idPrefix="YEAR" containerClass="CONTAINER" cacheRegion="local_default">				
				<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesForCreationYearCommand" idPrefix="I" itemClass="PHOTO" cacheRegion="local_default" />
			</action>			
		</container>
		<container title_key="month" id="I_T" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesCreationYearsCommand" idPrefix="YEAR" containerClass="CONTAINER" cacheRegion="local_default">				
				<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesCreationMonthsCommand" idPrefix="MON" containerClass="CONTAINER" cacheRegion="local_default">
					<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesForCreationMonthAndYearCommand" idPrefix="I" itemClass="PHOTO" cacheRegion="local_default" />				
				</action>
			</action>			
		</container>
		<container title_key="playlists" id="I_PL" editable="true" containerClass="CONTAINER" cacheRegion="local_default">
			<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagePlaylistsCommand" idPrefix="PL" containerClass="PLAYLIST_CONTAINER" cacheRegion="local_default">
				<action command="org.serviio.upnp.service.contentdirectory.command.image.ListImagesForPlaylistCommand" idPrefix="S" itemClass="PHOTO" cacheRegion="local_default"/>
			</action>
		</container>	 
		<container title_key="online" id="I_OF" editable="true" containerClass="CONTAINER" cacheRegion="no_cache">
